
language: node_js
node_js:
  - "7"
cache: npm

install:
  - npm install
  - npm install coveralls

script:
  - npm test
  - npm run coverage
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls
